server:
  port: 9000

spring:
  application:
    name: user-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/weather
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # options: validate, update, create, create-drop
    show-sql: true  # to show SQL queries in the console
    properties:
      hibernate:
        format_sql: true  # format SQL queries for readability

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka server URL